ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "hourlyRate" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "federalStatus" TEXT DEFAULT 'S',
  ADD COLUMN IF NOT EXISTS "stateStatus" TEXT DEFAULT 'S-00',
  ADD COLUMN IF NOT EXISTS "federalTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "stateTaxPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "otherDeductionMonthly" DOUBLE PRECISION NOT NULL DEFAULT 0;
